version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core:v5.1.0
    container_name: v2ray_upstream
    restart: always
    command: [ "v2ray","run", "-c", "/etc/v2ray/config.json" ]
    ports:
      - 80:80
      - 100:100
      - 1355:1355
      # - 84:84
      # - 85:85
      # - 86:86
    volumes:
      - ./config/:/etc/v2ray/:ro